#!/bin/bash


# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF

  Usage: $0 [command]

  Commands:

  debug     - Starts all containers and attach logs.
  start     - Starts all containers.
  restart   - Brings down the services and removes the volumes (storage) and containers then starts all containers.
  stop      - Brings down the services and removes the volumes (storage) and containers.

EOF
exit 1
}

COMMAND=${1}

case "${COMMAND}" in
  debug)
sudo docker compose --env-file .env.demo up --build
    ;;
  start)
sudo docker compose --env-file .env.demo up --build -d
    ;;
  restart)
sudo docker compose --env-file .env.demo down -v
sudo docker compose --env-file .env.demo up --build -d
    ;;
  stop)
sudo docker compose --env-file .env.demo down -v
    ;;
  *)
      usage;;
esac